### ISSUE TITLE
Downgrading tools does not happen

### ISSUE THREAD

**Issue by cmug81** [voxpupuli/puppet-vmwaretools#34]
I want to downgrade from 'latest' to '5.5latest'. This does not seem to happen when I change tools_version => '5.5latest' and autoupgrade => 'false', instead the latest RPM files are still found on the system.

Is it supposed to be possible to downgrade tools version?

reason for downgrading is that we seem to be hitting a bug with latest tools that causes VM's to crash when quiescing filesystem for backup.

**Comment by razorsedge** [comment]
@cmug81 This module is not capable of downgrading packages.  The `tools_version` merely sets the YUM/APT/Zypp repo configuration.
